name: Gestao de Vagas Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build project
        run: mvn clean install
      - name: Login docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker imagem
        run: docker build -t guilhermemelolima/gestao_vagas .
      - name: Publish imagem
        run: docker push guilhermemelolima/gestao_vagas